apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: bd-demo
spec:
  containers:
    - name: opa-repo
      image: openpolicyagent/opa:0.9.2
      args:
        - "run" 
        - "--server" 
        - "--addr=localhost:8080"
